pages:
  stage: deploy
  image: node:16.20.2
  script:
    - mkdir .public
    - npm config set registry https://registry.npmmirror.com/
    - npm install
    - npm run build
    - cp -r ./dist/* .public
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

